name: Labels

on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: EddieHubCommunity labels Action
      uses: EddieHubCommunity/gh-action-open-source-labels@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: 'Alphasians'
        repository-name: ${{ github.event.repository.name }}
